# WhisperPaw shell completions for fish.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('fish'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


# Auto-generated completions for paw-read.
complete -c paw-read -l file -d 'Read text from this UTF-8 file instead of positional args.'
complete -c paw-read -l clipboard -d 'Read text from the system clipboard.'
complete -c paw-read -l rate -d 'Speech rate, words per minute (80–600, default: 200).'
complete -c paw-read -l volume -d 'Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).'
complete -c paw-read -l max-chars -d 'Soft max chars per spoken chunk (default: 200).'
complete -c paw-read -l backend -d 'TTS backend to use.'
complete -c paw-read -l piper-voice -d 'Path to a Piper .onnx voice model.'
complete -c paw-read -l list-backends -d 'Print the names of every supported TTS backend, one per line, and exit.'
complete -c paw-read -l list-voices -d 'Print the absolute path of every Piper .onnx voice model found in the well-know…'
complete -c paw-read -l json -d 'Combine with --list-backends or --list-voices to emit a JSON object instead of…'
complete -c paw-read -l quiet -d 'Suppress the announcement line (still speaks).'

# Auto-generated completions for paw-sound.
complete -c paw-sound -l pack -d 'Sound pack to use.'
complete -c paw-sound -l volume -d 'Playback volume, 0.0–1.0 (default: 0.6).'
complete -c paw-sound -l quiet -d 'Suppress the announcement line (still plays the sound).'
complete -c paw-sound -l list-packs -d 'Print the names of every available sound pack, one per line, and exit.'
complete -c paw-sound -l list-events -d 'Print the names of every known event, one per line, and exit.'
complete -c paw-sound -l json -d 'Combine with --list-packs or --list-events to emit a JSON object instead of one…'

# Auto-generated completions for paw-watch.
complete -c paw-watch -l rate -d 'Speech rate, words per minute (80–600, default: 200).'
complete -c paw-watch -l volume -d 'Playback volume, 0.0–1.0 (default: 1.0).'
complete -c paw-watch -l max-lines -d 'Speak at most this many lines (0 = unlimited, default: 0).'
complete -c paw-watch -l include-stderr -d 'Also speak lines that arrive on stderr (in addition to stdout).'
complete -c paw-watch -l quiet -d 'Suppress the announcement line (still speaks).'
complete -c paw-watch -l follow -d 'Stream the output instead of waiting for the command to finish: each new line i…'
complete -c paw-watch -l dry-run -d 'Print each line that *would* be spoken to stdout, one per line, instead of call…'

# Auto-generated completions for paw-zoom.
complete -c paw-zoom -l file -d 'Read text from this UTF-8 file instead of positional args.'
complete -c paw-zoom -l rows -d 'How many source rows to show (default: 10, must be >= 1).'
complete -c paw-zoom -l cols -d 'How many source columns to show (default: 40, must be >= 1).'
complete -c paw-zoom -l offset -d 'Starting row in the source (default: 0).'
complete -c paw-zoom -l col-offset -d 'Starting column in the source (default: 0).'
complete -c paw-zoom -l zoom -d 'Magnification factor: each source cell becomes a --zoom×--zoom block (default:…'
complete -c paw-zoom -l charset -d 'Fill character for empty cells: \'space\' (default, invisible), \'hash\' (#), or \'d…'
complete -c paw-zoom -l line-numbers -d 'Prefix each magnified source row with its 1-based row number (right-aligned in…'
complete -c paw-zoom -l quiet -d 'Suppress the announcement line (still renders).'
complete -c paw-zoom -l snapshot -d 'Write the rendered viewport to PATH instead of stdout.'
complete -c paw-zoom -l live -d 'Follow the source like \'tail -f\': re-render the magnified viewport every time i…'
complete -c paw-zoom -l interval -d 'Poll interval in seconds for --live (default: 0.25, must be > 0).'
complete -c paw-zoom -l follow -d 'Track the tail of --file PATH (like \'tail -f\') instead of showing the start.'
complete -c paw-zoom -l max-frames -d 'Cap --live at N loop iterations (default: 0 = unlimited, the current behaviour).'
complete -c paw-zoom -l max-seconds -d 'Cap --live at SECS wall-clock seconds (default: 0 = unlimited, the current beha…'
complete -c paw-zoom -l raw -d 'Dump the source (text or screen) to stdout as plain text, with no magnification…'
complete -c paw-zoom -l size -d 'Print the source dimensions (rows x cols, in code points) and exit 0 without re…'
complete -c paw-zoom -l stats -d 'Print per-source statistics (chars, lines, non-blank lines, max line width, mea…'
complete -c paw-zoom -l sha -d 'Print a stable hex digest of the source (default: SHA-256, 64 lowercase hex cha…'
complete -c paw-zoom -l sha-algo -d 'Hash algorithm for --sha (default: sha256).'
complete -c paw-zoom -l screen -d 'Capture a rectangular region of the visual screen and magnify it, instead of ma…'
complete -c paw-zoom -l region -d 'Screen rectangle to capture when --screen is set.'
complete -c paw-zoom -l backend -d 'Screen-capture backend to use when --screen is set (default: auto — picks the f…'
complete -c paw-zoom -l fake-grid -d 'With --backend fake, the text used as the \'screen\' (rows separated by \'\n\').'
complete -c paw-zoom -l list-backends -d 'Print the names of every supported screen-capture backend, one per line, and ex…'
complete -c paw-zoom -l info -d 'Print a short description of the screen-capture setup this invocation would use…'
complete -c paw-zoom -l json -d 'Combine with --list-backends, --info, --size, or --stats to emit a single-line…'
