# WhisperPaw shell completions for bash.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('bash'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


_paw_read_flags() {
  COMPREPLY=(--file --clipboard --rate --volume --max-chars --backend --piper-voice --list-backends --list-voices --json --quiet)
}
_paw_complete_paw_read() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == --* ]]; then
    COMPREPLY=($(compgen -W '--file --clipboard --rate --volume --max-chars --backend --piper-voice --list-backends --list-voices --json --quiet' -- "$cur"))
    return 0
  fi
  # No subcommands; nothing else to complete.
  return 0
}
complete -F _paw_complete_paw_read paw-read

_paw_sound_flags() {
  COMPREPLY=(--pack --volume --quiet --list-packs --list-events --json)
}
_paw_complete_paw_sound() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == --* ]]; then
    COMPREPLY=($(compgen -W '--pack --volume --quiet --list-packs --list-events --json' -- "$cur"))
    return 0
  fi
  # No subcommands; nothing else to complete.
  return 0
}
complete -F _paw_complete_paw_sound paw-sound

_paw_watch_flags() {
  COMPREPLY=(--rate --volume --max-lines --include-stderr --quiet --follow --dry-run)
}
_paw_complete_paw_watch() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == --* ]]; then
    COMPREPLY=($(compgen -W '--rate --volume --max-lines --include-stderr --quiet --follow --dry-run' -- "$cur"))
    return 0
  fi
  # No subcommands; nothing else to complete.
  return 0
}
complete -F _paw_complete_paw_watch paw-watch

_paw_zoom_flags() {
  COMPREPLY=(--file --rows --cols --offset --col-offset --zoom --charset --quiet --snapshot --live --interval --follow --max-frames --raw --screen --region --backend --fake-grid --list-backends --info --json)
}
_paw_complete_paw_zoom() {
  local cur prev
  cur="${COMP_WORDS[COMP_CWORD]}"
  if [[ "$cur" == --* ]]; then
    COMPREPLY=($(compgen -W '--file --rows --cols --offset --col-offset --zoom --charset --quiet --snapshot --live --interval --follow --max-frames --raw --screen --region --backend --fake-grid --list-backends --info --json' -- "$cur"))
    return 0
  fi
  # No subcommands; nothing else to complete.
  return 0
}
complete -F _paw_complete_paw_zoom paw-zoom
