# WhisperPaw shell completions for fish.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('fish'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


# Auto-generated completions for paw-read.
complete -c paw-read -l file -d 'Read text from this UTF-8 file instead of positional args.'
complete -c paw-read -l clipboard -d 'Read text from the system clipboard.'
complete -c paw-read -l rate -d 'Speech rate, words per minute (80–600, default: 200).'
complete -c paw-read -l volume -d 'Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).'
complete -c paw-read -l max-chars -d 'Soft max chars per spoken chunk (default: 200).'
complete -c paw-read -l backend -d 'TTS backend to use.'
complete -c paw-read -l piper-voice -d 'Path to a Piper .onnx voice model.'
complete -c paw-read -l quiet -d 'Suppress the announcement line (still speaks).'

# Auto-generated completions for paw-sound.
complete -c paw-sound -l pack -d 'Sound pack to use.'
complete -c paw-sound -l volume -d 'Playback volume, 0.0–1.0 (default: 0.6).'
complete -c paw-sound -l quiet -d 'Suppress the announcement line (still plays the sound).'
complete -c paw-sound -l list-packs -d 'Print the names of every available sound pack, one per line, and exit.'
complete -c paw-sound -l list-events -d 'Print the names of every known event, one per line, and exit.'

# Auto-generated completions for paw-watch.
complete -c paw-watch -l rate -d 'Speech rate, words per minute (80–600, default: 200).'
complete -c paw-watch -l volume -d 'Playback volume, 0.0–1.0 (default: 1.0).'
complete -c paw-watch -l max-lines -d 'Speak at most this many lines (0 = unlimited, default: 0).'
complete -c paw-watch -l include-stderr -d 'Also speak lines that arrive on stderr (in addition to stdout).'
complete -c paw-watch -l quiet -d 'Suppress the announcement line (still speaks).'
complete -c paw-watch -l follow -d 'Stream the output instead of waiting for the command to finish: each new line i…'

# paw-zoom: no completion data yet (build_parser() missing).
complete -c paw-zoom -f
