# WhisperPaw shell completions for zsh.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('zsh'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


#compdef paw-read
# Auto-generated for paw-read from its argparse parser.
_paw_read() {
  _arguments -s \
    '--file[Read text from this UTF-8 file instead of positional args.]' \
    '--clipboard[Read text from the system clipboard.]' \
    '--rate[Speech rate, words per minute (80–600, default: 200).]' \
    '--volume[Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).]' \
    '--max-chars[Soft max chars per spoken chunk (default: 200).]' \
    '--backend[TTS backend to use.]' \
    '--piper-voice[Path to a Piper .onnx voice model.]' \
    '--list-backends[Print the names of every supported TTS backend, one per line, and exit.]' \
    '--list-voices[Print the absolute path of every Piper .onnx voice model found in the well-know…]' \
    '--json[Combine with --list-backends or --list-voices to emit a JSON object instead of…]' \
    '--quiet[Suppress the announcement line (still speaks).]'
}
_paw_read "$@"

#compdef paw-sound
# Auto-generated for paw-sound from its argparse parser.
_paw_sound() {
  _arguments -s \
    '--pack[Sound pack to use.]' \
    '--volume[Playback volume, 0.0–1.0 (default: 0.6).]' \
    '--quiet[Suppress the announcement line (still plays the sound).]' \
    '--list-packs[Print the names of every available sound pack, one per line, and exit.]' \
    '--list-events[Print the names of every known event, one per line, and exit.]' \
    '--json[Combine with --list-packs or --list-events to emit a JSON object instead of one…]'
}
_paw_sound "$@"

#compdef paw-watch
# Auto-generated for paw-watch from its argparse parser.
_paw_watch() {
  _arguments -s \
    '--rate[Speech rate, words per minute (80–600, default: 200).]' \
    '--volume[Playback volume, 0.0–1.0 (default: 1.0).]' \
    '--max-lines[Speak at most this many lines (0 = unlimited, default: 0).]' \
    '--include-stderr[Also speak lines that arrive on stderr (in addition to stdout).]' \
    '--quiet[Suppress the announcement line (still speaks).]' \
    '--follow[Stream the output instead of waiting for the command to finish: each new line i…]' \
    '--dry-run[Print each line that *would* be spoken to stdout, one per line, instead of call…]'
}
_paw_watch "$@"

#compdef paw-zoom
# Auto-generated for paw-zoom from its argparse parser.
_paw_zoom() {
  _arguments -s \
    '--file[Read text from this UTF-8 file instead of positional args.]' \
    '--rows[How many source rows to show (default: 10, must be >= 1).]' \
    '--cols[How many source columns to show (default: 40, must be >= 1).]' \
    '--offset[Starting row in the source (default: 0).]' \
    '--col-offset[Starting column in the source (default: 0).]' \
    '--zoom[Magnification factor: each source cell becomes a --zoom×--zoom block (default:…]' \
    '--charset[Fill character for empty cells: ''space'' (default, invisible), ''hash'' (#), or ''d…]' \
    '--quiet[Suppress the announcement line (still renders).]' \
    '--snapshot[Write the rendered viewport to PATH instead of stdout.]' \
    '--live[Follow the source like ''tail -f'': re-render the magnified viewport every time i…]' \
    '--interval[Poll interval in seconds for --live (default: 0.25, must be > 0).]' \
    '--follow[Track the tail of --file PATH (like ''tail -f'') instead of showing the start.]' \
    '--max-frames[Cap --live at N loop iterations (default: 0 = unlimited, the current behaviour).]' \
    '--raw[Dump the source (text or screen) to stdout as plain text, with no magnification…]' \
    '--size[Print the source dimensions (rows x cols, in code points) and exit 0 without re…]' \
    '--screen[Capture a rectangular region of the visual screen and magnify it, instead of ma…]' \
    '--region[Screen rectangle to capture when --screen is set.]' \
    '--backend[Screen-capture backend to use when --screen is set (default: auto — picks the f…]' \
    '--fake-grid[With --backend fake, the text used as the ''screen'' (rows separated by ''\n'').]' \
    '--list-backends[Print the names of every supported screen-capture backend, one per line, and ex…]' \
    '--info[Print a short description of the screen-capture setup this invocation would use…]' \
    '--json[Combine with --list-backends, --info, or --size to emit a single-line JSON obje…]'
}
_paw_zoom "$@"
