# WhisperPaw shell completions for nu.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('nu'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


# Auto-generated external completer for paw-read.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-read" [
    --file: string  # Read text from this UTF-8 file instead of positional args.
    --clipboard: string  # Read text from the system clipboard.
    --rate: string  # Speech rate, words per minute (80–600, default: 200).
    --volume: string  # Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).
    --max-chars: string  # Soft max chars per spoken chunk (default: 200).
    --backend: string  # TTS backend to use.
    --piper-voice: string  # Path to a Piper .onnx voice model.
    --quiet: string  # Suppress the announcement line (still speaks).
]

# Auto-generated external completer for paw-sound.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-sound" [
    --pack: string  # Sound pack to use.
    --volume: string  # Playback volume, 0.0–1.0 (default: 0.6).
    --quiet: string  # Suppress the announcement line (still plays the sound).
]

# Auto-generated external completer for paw-watch.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-watch" [
    --rate: string  # Speech rate, words per minute (80–600, default: 200).
    --volume: string  # Playback volume, 0.0–1.0 (default: 1.0).
    --max-lines: string  # Speak at most this many lines (0 = unlimited, default: 0).
    --include-stderr: string  # Also speak lines that arrive on stderr (in addition to stdout).
    --quiet: string  # Suppress the announcement line (still speaks).
    --follow: string  # Stream the output instead of waiting for the command to finish: each new line i…
]

# paw-zoom: no completion data yet (build_parser() missing).
extern "paw-zoom" []

