# WhisperPaw shell completions for nu.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('nu'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


# Auto-generated external completer for paw-read.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-read" [
    --file: string  # Read text from this UTF-8 file instead of positional args.
    --clipboard: string  # Read text from the system clipboard.
    --rate: string  # Speech rate, words per minute (80–600, default: 200).
    --volume: string  # Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).
    --max-chars: string  # Soft max chars per spoken chunk (default: 200).
    --backend: string  # TTS backend to use.
    --piper-voice: string  # Path to a Piper .onnx voice model.
    --quiet: string  # Suppress the announcement line (still speaks).
]

# Auto-generated external completer for paw-sound.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-sound" [
    --pack: string  # Sound pack to use.
    --volume: string  # Playback volume, 0.0–1.0 (default: 0.6).
    --quiet: string  # Suppress the announcement line (still plays the sound).
    --list-packs: string  # Print the names of every available sound pack, one per line, and exit.
    --list-events: string  # Print the names of every known event, one per line, and exit.
]

# Auto-generated external completer for paw-watch.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-watch" [
    --rate: string  # Speech rate, words per minute (80–600, default: 200).
    --volume: string  # Playback volume, 0.0–1.0 (default: 1.0).
    --max-lines: string  # Speak at most this many lines (0 = unlimited, default: 0).
    --include-stderr: string  # Also speak lines that arrive on stderr (in addition to stdout).
    --quiet: string  # Suppress the announcement line (still speaks).
    --follow: string  # Stream the output instead of waiting for the command to finish: each new line i…
]

# Auto-generated external completer for paw-zoom.
# Add this file's contents to your config.nu, or `source` it from there.
extern "paw-zoom" [
    --file: string  # Read text from this UTF-8 file instead of positional args.
    --rows: string  # How many source rows to show (default: 10, must be >= 1).
    --cols: string  # How many source columns to show (default: 40, must be >= 1).
    --offset: string  # Starting row in the source (default: 0).
    --col-offset: string  # Starting column in the source (default: 0).
    --zoom: string  # Magnification factor: each source cell becomes a --zoom×--zoom block (default:…
    --charset: string  # Fill character for empty cells: 'space' (default, invisible), 'hash' (#), or 'd…
    --quiet: string  # Suppress the announcement line (still renders).
]
