# WhisperPaw shell completions for zsh.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('zsh'), end='')"
# Subcommands covered: paw-read paw-sound paw-watch paw-zoom
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md


#compdef paw-read
# Auto-generated for paw-read from its argparse parser.
_paw_read() {
  _arguments -s \
    '--file[Read text from this UTF-8 file instead of positional args.]' \
    '--clipboard[Read text from the system clipboard.]' \
    '--rate[Speech rate, words per minute (80–600, default: 200).]' \
    '--volume[Playback volume, 0.0–1.0 (default: 1.0; ignored on Windows).]' \
    '--max-chars[Soft max chars per spoken chunk (default: 200).]' \
    '--backend[TTS backend to use.]' \
    '--piper-voice[Path to a Piper .onnx voice model.]' \
    '--quiet[Suppress the announcement line (still speaks).]'
}
_paw_read "$@"

#compdef paw-sound
# Auto-generated for paw-sound from its argparse parser.
_paw_sound() {
  _arguments -s \
    '--pack[Sound pack to use.]' \
    '--volume[Playback volume, 0.0–1.0 (default: 0.6).]' \
    '--quiet[Suppress the announcement line (still plays the sound).]' \
    '--list-packs[Print the names of every available sound pack, one per line, and exit.]' \
    '--list-events[Print the names of every known event, one per line, and exit.]'
}
_paw_sound "$@"

#compdef paw-watch
# Auto-generated for paw-watch from its argparse parser.
_paw_watch() {
  _arguments -s \
    '--rate[Speech rate, words per minute (80–600, default: 200).]' \
    '--volume[Playback volume, 0.0–1.0 (default: 1.0).]' \
    '--max-lines[Speak at most this many lines (0 = unlimited, default: 0).]' \
    '--include-stderr[Also speak lines that arrive on stderr (in addition to stdout).]' \
    '--quiet[Suppress the announcement line (still speaks).]' \
    '--follow[Stream the output instead of waiting for the command to finish: each new line i…]'
}
_paw_watch "$@"

#compdef paw-zoom
# paw-zoom: no completion data yet (build_parser() missing).
_paw_zoom() { _files }
_paw_zoom "$@"
