"""Shell completions for the ``paw-*`` tools.

Why this lives in its own module
--------------------------------
Each ``paw-*`` tool already has an ``argparse.ArgumentParser`` built by
``build_parser()`` — and that parser is the single source of truth for
what the tool accepts. This module introspects every tool's parser and
emits shell-specific completion code so:

* the completion list can never drift from the real flags, and
* adding a new flag to a tool picks up completion automatically next
  time ``paw-complete`` is re-sourced.

The output of this module is what gets printed by ``paw-complete
{shell}``. The same text is also checked into
``completions/whisperpaw.{bash,zsh,fish,nu}`` so users on systems where
they can't run Python at shell-startup time (e.g. a stripped-down git
bash on Windows) can still drop a static file into their
``$XDG_CONFIG_HOME`` directory. A test in
``tests/test_completions.py`` asserts the shipped static files are
byte-identical to the live generator output.

Supported shells:

* ``bash``  — uses ``complete -F`` (bash ≥ 3.2). Output is a single
  shell function that the user ``source``s.
* ``zsh``   — uses ``#compdef paw-…`` + ``_describe``. Output is a
  single autoload-style file the user drops into ``$fpath``.
* ``fish``  — uses ``complete -c paw-…``. Output is a single
  ``completions/paw-*.fish`` file.
* ``nu``    — nushell ``external completer`` block. Output is a
  ``paw-*.nu`` file the user ``source``s.

For every shell, the entry is the **subcommand name** (``paw-read``,
``paw-sound`` …). We deliberately do not try to provide a single
``paw`` parent dispatcher because each subcommand is a separate
``console_scripts`` entry point — users will type
``paw-read --r<TAB>``, not ``paw read --r<TAB>``.
"""
from __future__ import annotations

import argparse
import importlib
from dataclasses import dataclass
from typing import Callable, Iterable, Sequence


#: The list of (module-name, CLI name) pairs we know about. New tools
#: should be added here. Tools without a ``build_parser()`` (e.g. still
#: stubs) are listed with ``has_parser=False`` so the completion files
#: still build, but they emit a minimal "no flags yet" entry.
@dataclass(frozen=True)
class _Tool:
    module: str
    prog: str
    has_parser: bool = True


_TOOLS: tuple[_Tool, ...] = (
    _Tool("whisperpaw.read", "paw-read"),
    _Tool("whisperpaw.sound", "paw-sound"),
    _Tool("whisperpaw.watch", "paw-watch"),
    _Tool("whisperpaw.zoom", "paw-zoom", has_parser=False),
)


SUPPORTED_SHELLS: tuple[str, ...] = ("bash", "zsh", "fish", "nu")


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------


def list_tools() -> list[str]:
    """Return the list of subcommand names we ship completions for."""
    return [t.prog for t in _TOOLS]


def render(shell: str) -> str:
    """Render completion code for ``shell`` (``bash`` / ``zsh`` /
    ``fish`` / ``nu``).

    Raises :class:`ValueError` for unknown shells. The output is plain
    text (no ANSI escapes), suitable for redirecting into a file.
    """
    if shell not in SUPPORTED_SHELLS:
        raise ValueError(
            f"unsupported shell: {shell!r} "
            f"(supported: {', '.join(SUPPORTED_SHELLS)})"
        )
    renderer = _RENDERERS[shell]
    # Render each tool's completion, joined with a blank line so the
    # output stays readable when concatenated.
    pieces = [renderer(t) for t in _TOOLS]
    header = _HEADER_TEMPLATE.format(
        shell=shell,
        tools=" ".join(t.prog for t in _TOOLS),
    )
    return header + "\n\n" + "\n\n".join(pieces) + "\n"


def render_all() -> dict[str, str]:
    """Render every supported shell at once. Returned as a ``{shell: text}`` dict."""
    return {shell: render(shell) for shell in SUPPORTED_SHELLS}


# ---------------------------------------------------------------------------
# Internals
# ---------------------------------------------------------------------------


_HEADER_TEMPLATE = """\
# WhisperPaw shell completions for {shell}.
#
# AUTO-GENERATED by whisperpaw._completions.render() — do not edit by hand.
# Regenerate with:
#     python -c "from whisperpaw._completions import render; print(render('{shell}'), end='')"
# Subcommands covered: {tools}
#
# For setup instructions, see:
# https://github.com/raincatgirl/WhisperPaw/blob/main/completions/README.md
"""


def _load_parser(module_name: str) -> argparse.ArgumentParser | None:
    """Import ``module_name`` and return its ``build_parser()`` result,
    or ``None`` if the module doesn't expose one yet (e.g. it's still
    a stub)."""
    try:
        mod = importlib.import_module(module_name)
    except Exception:
        return None
    builder: Callable[[], argparse.ArgumentParser] | None = getattr(
        mod, "build_parser", None
    )
    if builder is None:
        return None
    try:
        return builder()
    except Exception:
        return None


def _truncate_help(help_text: str, limit: int = 80) -> str:
    """Shorten a help string to ``limit`` characters for compactness.

    We split on the first sentence boundary (``. `` / ``! `` / ``? ``
    followed by a space) — NOT on a bare period, because ranges like
    ``0.0–1.0`` and version numbers ``0.0.1`` would otherwise get
    chopped in the middle.
    """
    text = (help_text or "").strip()
    if not text:
        return ""
    # Find the earliest sentence-boundary separator that is followed
    # by whitespace. If we find one, end the string right before it.
    for sep in (". ", "! ", "? "):
        idx = text.find(sep)
        if idx != -1:
            text = text[:idx + 1]
            break
    if len(text) > limit:
        text = text[: limit - 1].rstrip() + "…"
    return text


def _collect_flags(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    """Return a list of ``(flag, help)`` pairs for every option the
    parser knows about. Skips ``--help`` (every shell handles that
    itself)."""
    out: list[tuple[str, str]] = []
    for action in parser._actions:  # noqa: SLF001 — argparse public-ish API
        if action.dest in ("help", "==SUPPRESS=="):
            continue
        for opt in action.option_strings:
            out.append((opt, _truncate_help(action.help or "")))
    return out


def _collect_positionals(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    """Return ``(name, choices_or_help)`` for every positional."""
    out: list[tuple[str, str]] = []
    for action in parser._actions:  # noqa: SLF001
        if not action.option_strings:
            if action.choices:
                out.append((action.dest, ", ".join(str(c) for c in action.choices)))
            else:
                out.append((action.dest, _truncate_help(action.help or "")))
    return out


# ---------------------------------------------------------------------------
# Per-shell renderers
# ---------------------------------------------------------------------------


def _render_bash(tool: _Tool) -> str:
    parser = _load_parser(tool.module)
    flags = _collect_flags(parser) if parser is not None else []
    positionals = _collect_positionals(parser) if parser is not None else []

    if parser is None:
        # Stub: emit a no-op completion so sourcing the file does not error.
        return (
            f"# {tool.prog}: no completion data yet (build_parser() missing).\n"
            f"_{tool.prog.replace('-', '_')}() {{ :; }}\n"
            f"complete -F _{tool.prog.replace('-', '_')} {tool.prog} 2>/dev/null || true"
        )

    fn_name = "_paw_complete_" + tool.prog.replace("-", "_")
    # compgen -W wants a single space-separated string of words; the
    # double-quoting in the earlier draft made it one giant token.
    # Each flag is shell-safe (starts with --, no spaces), so we just
    # join with a literal space.
    flag_words = " ".join(f for f, _ in flags)
    return (
        f"_{tool.prog.replace('-', '_')}_flags() {{\n"
        f"  COMPREPLY=({flag_words})\n"
        f"}}\n"
        f"{fn_name}() {{\n"
        f"  local cur prev\n"
        f"  cur=\"${{COMP_WORDS[COMP_CWORD]}}\"\n"
        f"  if [[ \"$cur\" == --* ]]; then\n"
        f"    COMPREPLY=($(compgen -W '{flag_words}' -- \"$cur\"))\n"
        f"    return 0\n"
        f"  fi\n"
        f"  # No subcommands; nothing else to complete.\n"
        f"  return 0\n"
        f"}}\n"
        f"complete -F {fn_name} {tool.prog}"
    )


def _render_zsh(tool: _Tool) -> str:
    parser = _load_parser(tool.module)
    flags = _collect_flags(parser) if parser is not None else []
    positionals = _collect_positionals(parser) if parser is not None else []

    if parser is None:
        return (
            f"#compdef {tool.prog}\n"
            f"# {tool.prog}: no completion data yet (build_parser() missing).\n"
            f"_{tool.prog.replace('-', '_')}() {{ _files }}\n"
            f"_{tool.prog.replace('-', '_')} \"$@\""
        )

    fn_name = "_" + tool.prog.replace("-", "_")
    lines: list[str] = [
        f"#compdef {tool.prog}",
        f"# Auto-generated for {tool.prog} from its argparse parser.",
        f"{fn_name}() {{",
        f"  _arguments -s \\",
    ]
    for flag, help_text in flags:
        # Strip the surrounding quotes from help_text if any.
        safe = help_text.replace("'", "''")
        if flag.startswith("--"):
            lines.append(f"    '{flag}[{safe}]' \\")
        else:
            lines.append(f"    '{flag}[{safe}]' \\")
    # Drop the trailing backslash from the last flag.
    if lines[-1].rstrip().endswith("\\"):
        lines[-1] = lines[-1].rstrip().rstrip("\\").rstrip()
    # Close the function and call it.
    lines.extend([
        "}",
        f"{fn_name} \"$@\"",
    ])
    return "\n".join(lines)


def _render_fish(tool: _Tool) -> str:
    parser = _load_parser(tool.module)
    flags = _collect_flags(parser) if parser is not None else []
    positionals = _collect_positionals(parser) if parser is not None else []

    if parser is None:
        return (
            f"# {tool.prog}: no completion data yet (build_parser() missing).\n"
            f"complete -c {tool.prog} -f"
        )

    lines: list[str] = [f"# Auto-generated completions for {tool.prog}."]
    for flag, help_text in flags:
        safe = help_text.replace("'", "\\'")
        lines.append(f"complete -c {tool.prog} -l {flag.lstrip('-')} -d '{safe}'")
    return "\n".join(lines)


def _render_nu(tool: _Tool) -> str:
    """Emit a nushell external-command completer.

    nushell's real syntax for declaring an external completer is
    ``extern "<name>" [ --flag: type ]``. The block we emit here is
    not a callable function — it tells nushell "this name refers to
    an external binary, and here are its flags", which is what
    drives completion at the prompt.

    We deliberately use ``string`` for every flag's type because (a)
    the underlying argparse parsers don't expose type information in
    a way we can map cleanly, and (b) nushell itself only needs the
    flag name to drive completion; the value is a real string the
    user types or a file path the user picks from a glob.
    """
    parser = _load_parser(tool.module)
    flags = _collect_flags(parser) if parser is not None else []

    if parser is None:
        return (
            f"# {tool.prog}: no completion data yet (build_parser() missing).\n"
            f"extern \"{tool.prog}\" []\n"
        )

    lines: list[str] = [
        f"# Auto-generated external completer for {tool.prog}.",
        f"# Add this file's contents to your config.nu, or `source` it from there.",
        f'extern "{tool.prog}" [',
    ]
    for flag, help_text in flags:
        # The flag name (without the leading --) becomes the nushell
        # flag. help_text is added as a nushell comment so the user
        # sees it in the completer; we strip single quotes to avoid
        # breaking the nushell source.
        safe = help_text.replace('"', '\\"')
        long_name = flag.lstrip("-")
        lines.append(f"    --{long_name}: string  # {safe}")
    if not flags:
        lines.append("    # (no flags yet)")
    lines.append("]")
    return "\n".join(lines)


_RENDERERS: dict[str, Callable[[_Tool], str]] = {
    "bash": _render_bash,
    "zsh": _render_zsh,
    "fish": _render_fish,
    "nu": _render_nu,
}


__all__ = ["SUPPORTED_SHELLS", "list_tools", "render", "render_all"]
